version: '3.8'
services:
  server:
    build: .
    ports:
      - '3333:3333'
    depends_on:
      - postgres
  client:
    build: ./frontend
    ports:
      - '3000:3000'
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    ports:
      - 5454:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    depends_on:
      - redis
    env_file: .env
  redis:
    image: 'redis:alpine'
    ports:
      - 6379:${REDIS_PORT}
networks:
  nesjs-network:
