version: '3.8'
services:
  dev-db:
    image: postgres:13
    restart: always
    ports:
      - 5434:5434
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nest
